version: "3.8"
services:
  db:
    # container_name: "db"
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
        - db.env
    ports:
      - "15432:5432"
    networks:
      - main

  redis:
    # container_name: "redis"
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - main

  webapp:
    container_name: "template-webapp"
    build:
      context: ./
      dockerfile: apps/webapp/Dockerfile
      args:
        - GH_REGISTRY_TOKEN
    # image: my/template-server:staging
    profiles: ["webapp"]
    ports:
      - 3000:3000
    links:
      - "redis"
      - "db"
    env_file:
      - apps/webapp/docker.env
        # restart:
        #   unless-stopped
    command: /bin/bash -c "npm run start:prod"
    networks:
      - main
        #- traefik-hub
   # environment:
   #   - VIRTUAL_HOST=test.com

  #app-bubbles:
  #  container_name: "app-bubbles"
  #  build:
  #    context: ./
  #    dockerfile: apps/bubbles/Dockerfile
  #    args:
  #      - GH_REGISTRY_TOKEN
  #  # image: my/bubbles-server:staging
  #  profiles: ["bubbles"]
  #  ports:
  #    - 3000:3000
  #  links:
  #    - "redis"
  #    - "db"
  #  env_file:
  #    - apps/bubbles/docker.env
  #  restart:
  #    unless-stopped
  #  command: /bin/bash -c "npm run app:bubbles:prod"
  #  networks:
  #    - main
  # # environment:
  # #   - VIRTUAL_HOST=test.com

volumes:
  database:

networks:
  main:
    name: main
 #   driver: bridge
 #  traefik-hub:
 #    external: true
