version: "3.8"
services:
  db:
    container_name: "db"
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
        - db.env
    ports:
      - "15432:5432"
    networks:
      - main 
  redis:
    container_name: "redis"
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - main
  backend:
    container_name: "back"
    image: centergamedev/baikal-server:production
    ports:
      - 3000:3000
    links:
      - "redis"
      - "db"
    env_file:
      - docker.env
    restart:
      unless-stopped
    command: /bin/bash -c "npm run start:prod"
    networks:
      - main
      - proxy
    environment:
      - VIRTUAL_HOST=shop.forum-baikal.ru,baikal-backend.center-game.com
      - LETSENCRYPT_HOST=shop.forum-baikal.ru,baikal-backend.center-game.com
      - LETSENCRYPT_EMAIL=dev@center-game.com
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true

volumes:
  database:

networks:
  main:
    name: main
    driver: bridge
  proxy:
    external: true
