name: alfa test
on:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/deploy-app.yml
    with:
      app: alfa
      # webDomain: ""
      # dbDatabase: alfa
      environment: test
      # debug: "true"
    secrets:
      sshHost: ${{ secrets.ALFA_STAGE_SSH_HOST }}
      sshKey: ${{ secrets.ALFA_STAGE_SSH_KEY }}
      sshUser: ${{ secrets.ALFA_STAGE_SSH_USER }}
      GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      VAULT_URL: ${{ secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ secrets.ALFA_STAGE_VAULT_TOKEN }}
